#!/bin/bash
set -e

##########. WARNING. #################
## This is a hack. plain and simple.
## Do not try this at home.
######################################

PACKAGES_DIR=/var/vcap/packages
JOB_DIR=/var/vcap/jobs/uaa-customized

# Allow for > 128bit encryption
cp -a "${PACKAGES_DIR}"/jce-policy/UnlimitedJCEPolicyJDK8/*.jar "${PACKAGES_DIR}/uaa/jdk/jre/lib/security"

WARFILE="${PACKAGES_DIR}/uaa/tomcat/webapps/ROOT.war"
JARFILE=$(unzip -v "${WARFILE}" | grep cloudfoundry-identity-server- | awk '{print $8}')
WAR_TEMPDIR="$(mktemp -d)"

pushd "$WAR_TEMPDIR"
  unzip "$WARFILE" "$JARFILE"

  mkdir -p templates/web
  cp -a "$JOB_DIR"/<%= p("uaa-customized.template-directory") %>/web/* templates/web
  zip -r -u "$JARFILE" templates/web
  zip -u "$WARFILE" "$JARFILE"

  mkdir resources
  cp -a "$JOB_DIR"/<%= p("uaa-customized.template-directory") %>/resources/* resources/
  zip -r -u "$WARFILE" resources
popd

rm -rf "$WAR_TEMPDIR"
